name: fleetpy
channels:
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - attrs=24.2.0
  - babel=2.14.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - bidict=0.23.1
  - blinker=1.8.2
  - blosc=1.21.6
  - boost-cpp=1.78.0
  - branca=0.7.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.7.4
  - cairo=1.16.0
  - certifi=2024.7.4
  - cffi=1.17.0
  - cfitsio=4.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.2
  - contextily=1.6.0
  - contourpy=1.2.1
  - cryptography=42.0.2
  - curl=8.1.2
  - cycler=0.12.1
  - debugpy=1.8.5
  - decorator=5.1.1
  - dill=0.3.8
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fiona=1.9.1
  - flask=3.0.3
  - flask-socketio=5.3.6
  - folium=0.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1
  - freetype=2.12.1
  - freexl=1.0.6
  - future=1.0.0
  - gdal=3.6.2
  - geographiclib=2.0
  - geopandas=0.14.4
  - geopandas-base=0.14.4
  - geopy=2.4.1
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - ghp-import=2.1.0
  - giflib=5.2.2
  - glib=2.78.1
  - glib-tools=2.78.1
  - gst-plugins-base=1.22.7
  - gstreamer=1.22.7
  - gurobi=11.0.3
  - h11=0.14.0
  - h2=4.1.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.7
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipython_genutils=0.2.0
  - itsdangerous=2.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json-c=0.16
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kealib=1.5.0
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.1.2
  - libcxx=18.1.8
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgdal=3.6.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnetcdf=4.9.1
  - libnghttp2=1.58.0
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libpng=1.6.43
  - libpq=15.2
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=2.0.0
  - libspatialite=5.0.1
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libtiff=4.5.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzip=1.10.1
  - libzlib=1.3.1
  - livereload=2.7.0
  - llvm-openmp=18.1.8
  - llvmlite=0.43.0
  - lunr=0.7.0.post1
  - lz4-c=1.9.4
  - mapclassify=2.7.0
  - markdown=3.6
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mercantile=1.2.1
  - mergedeep=1.3.4
  - mkdocs=1.6.0
  - mkdocs-get-deps=0.2.0
  - mkdocs-material=9.5.31
  - mkdocs-material-extensions=1.3.1
  - munch=4.0.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nltk=3.8.1
  - nspr=4.35
  - nss=3.103
  - numba=0.60.0
  - numpy=1.26.4
  - olefile=0.47
  - openjpeg=2.5.0
  - openssl=3.1.6
  - packaging=24.1
  - paginate=0.5.6
  - pandas=2.2.2
  - parso=0.8.4
  - pathspec=0.12.1
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=24.2
  - pixman=0.43.4
  - platformdirs=4.2.2
  - ply=3.11
  - poppler=23.03.0
  - poppler-data=0.4.12
  - postgresql=15.2
  - proj=9.1.1
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pymdown-extensions=10.9
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pyproj=3.5.0
  - pyqt=5.15.9
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.9.0
  - python-engineio=4.9.1
  - python-socketio=5.11.3
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=306
  - pyyaml=6.0.2
  - pyyaml-env-tag=0.1
  - pyzmq=26.1.0
  - qhull=2020.2
  - qt=5.15.8
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - rasterio=1.3.6
  - readline=8.2
  - regex=2024.7.24
  - requests=2.32.3
  - rtree=1.3.0
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - setuptools=72.1.0
  - shapely=2.0.1
  - simple-websocket=1.0.0
  - sip=6.8.3
  - six=1.16.0
  - snappy=1.2.1
  - snuggs=1.4.7
  - sqlite=3.46.0
  - stack_data=0.6.2
  - tbb=2021.10.0
  - threadpoolctl=3.5.0
  - tiledb=2.13.2
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzcode=2024a
  - tzdata=2024a
  - uriparser=0.9.8
  - urllib3=2.2.2
  - watchdog=4.0.1
  - wcwidth=0.2.13
  - werkzeug=3.0.3
  - wheel=0.44.0
  - wsproto=1.2.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.14
      - pyqt5-sip==12.15.0
      - pyqt6==6.7.1
      - pyqt6-qt6==6.7.2
      - pyqt6-sip==13.8.0
      - pyqtwebengine==5.15.7
      - pyqtwebengine-qt5==5.15.14
