name: fleetpy
channels:
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - affine
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - boost-cpp
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - contextily
  - cryptography
  - curl
  - cycler
  - decorator
  - dill
  - expat
  - fiona
  - flask
  - flask-socketio
  - freetype
  - freexl
  - future
  - gdal
  - geographiclib
  - geopandas
  - geopy
  - geos
  - geotiff
  - gettext
  - glib
  - glib-tools
  - gurobi
  - hdf4
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - itsdangerous
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jupyter_client
  - jupyter_core
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - libblas
  - libcblas
  - libclang
  - libcurl
  - libffi
  - libgdal
  - libglib
  - libiconv
  - libkml
  - liblapack
  - libnetcdf
  - libpng
  - libpq
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libxml2
  - livereload
  - llvmlite
  - lunr
  - lz4-c
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mercantile
  - mkdocs
  - mkdocs-material
  - mkdocs-material-extensions
  - munch
  - networkx
  - nltk
  - numba
  - numpy
  - olefile
  - openjpeg
  - openssl
  - pandas
  - parso
  - pcre
  - pickleshare
  - pillow
  - pip
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prompt-toolkit
  - pycparser
  - pygments
  - pymdown-extensions
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pysocks
  - python
  - python-dateutil
  - python-engineio
  - python-socketio
  - python_abi
  - pytz
  - pywin32
  - pyyaml
  - pyzmq
  - qt
  - rasterio
  - regex
  - requests
  - rtree
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - snuggs
  - sqlite
  - tbb
  - threadpoolctl
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing_extensions
  - urllib3
  - wcwidth
  - werkzeug
  - wheel
  - xerces-c
  - xyzservices
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - pyqt5-sip
    - pyqt6
    - pyqt6-qt6
    - pyqt6-sip
    - pyqtwebengine
